### ISSUE TITLE
Messaging Queues

### ISSUE THREAD

**Issue by iivchenko** [CrazyCouple/TActive#12]
**TODO**
- RabbitMQ vs MSMQ
- RabbitMQ RPC vs WCF

**DOD**
- wiki page
- messaging prototype

**Comment by mtarcha** [comment]
Created pages https://github.com/CrazyCouple/TActive/wiki/RabbitMQ-vs-MSMQ
and https://github.com/CrazyCouple/TActive/wiki/RabbitMQ-RPC-vs--direct-call
